version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: gophermart_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: gophermart
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  accrual:
    image: debian:bullseye-slim
    container_name: gophermart_accrual
    volumes:
      - ./cmd/accrual:/app
    working_dir: /app
    entrypoint: ["/bin/bash", "-c"]
    command: ["apt-get update && apt-get install -y libc6-amd64-cross && ln -s /usr/x86_64-linux-gnu/lib64/ /lib64 && export LD_LIBRARY_PATH=\"$LD_LIBRARY_PATH:/lib64:/usr/x86_64-linux-gnu/lib\" && ./accrual_linux_amd64"]
    ports:
      - "8080:8080"
    platform: linux/amd64

  gophermart:
    image: golang:1.23-alpine
    container_name: gophermart_app
    volumes:
      - .:/app
    working_dir: /app
    command: ["sh", "-c", "apk add --no-cache git && go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest && cd /app && go mod tidy && go build -o /app/cmd/gophermart/gophermart /app/cmd/gophermart && /app/cmd/gophermart/gophermart"]
    ports:
      - "9090:9090"
    environment:
      - DATABASE_URI=postgres://postgres:secret@postgres:5432/gophermart?sslmode=disable
      - ACCRUAL_SYSTEM_ADDRESS=http://accrual:8080
      - JWT_SECRET_KEY=your-gophermart-jwt-secret-key
      - PATH=$PATH:/root/go/bin
    depends_on:
      postgres:
        condition: service_healthy

  migrate:
    image: migrate/migrate
    container_name: gophermart_migrate
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://postgres:secret@postgres:5432/gophermart?sslmode=disable", "up"]
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: