version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: gophermart_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: gophermart
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  accrual:
    image: alpine:latest
    container_name: gophermart_accrual
    volumes:
      - ./cmd/accrual:/app
    working_dir: /app
    command: ["./accrual_linux_amd64"]
    ports:
      - "8080:8080"

  gophermart:
    image: golang:1.23-alpine
    container_name: gophermart_app
    volumes:
      - .:/app
    working_dir: /app/cmd/gophermart
    command: ["./gophermart"]
    ports:
      - "9090:9090"
    environment:
      - DATABASE_URI=postgres://postgres:secret@postgres:5432/gophermart?sslmode=disable
      - ACCRUAL_SYSTEM_ADDRESS=http://accrual:8080

volumes:
  postgres_data: